databases:
  - name: postgres
    plan: free
    databaseName: ecommerce
    user: postgres

services:
  - type: web
    name: django-api
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn online_shop.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
