databases:
  - name: postgres
    plan: free
    databaseName: ecommerce
    user: postgres

services:
  - type: web
    name: django-api
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    # startCommand: "gunicorn your_project_name.asgi:application -k uvicorn.workers.UvicornWorker"
    startCommand: "waitress-serve --listen=0.0.0.0:8000 online_shop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
